### ISSUE TITLE
Send without being logged in?

### ISSUE THREAD

**Issue by Moondog360** [ranjanmp/django-channels2-notifications#1]
As the title states, where would I change the settings to send notifications to everyone whether logged in or not?

**Comment by ranjanmp** [comment]
This Article shows how to send realtime notifications to logged in users.
For sending notifications to users who are not logged in. I'd suggest you to create a new consumer in  consumers.py file which accepts connection from users who are not logged in and adds them to a common group. Create a new url for that consumer in the router.py file, again which accepts connection from the users which are not logged in.
Please have a look at the comments in the code in consumer.py file and router.py file where conditions have been added to accept connections from only logged in users. If you remove those conditions you'll be able to achieve what you are looking for.

I hope this answers your question.
